### ISSUE TITLE
strict objects option not working properly

### ISSUE THREAD

**Issue by typicalmike002** [koltyakov/sppull#11]
When using the strictObjects array, the siteUrl and spRootFolder values don't seem to be getting passed into the spFilePath parameter inside the operations.downloadFile method.  I can manually add them into the strings but your documentation indicates that this isn't required.

**Comment by koltyakov** [comment]
Hi Mike,

Thanks for pointing on that.
I hope it was fixed in 0.2.1.

Could you please check?

**Comment by typicalmike002** [comment]
Looks like the issue has been fixed in 0.2.1, Thank you!
