### ISSUE TITLE
using with typescript

### ISSUE THREAD

**Issue by thunder7553** [koltyakov/sppull#14]
Using the library with typescript and "import" does not seem to work. 

``` typescript
import * as sppull from 'sppull'
```

then if have a "Download" class, which cannot be instantiated.

**Comment by koltyakov** [comment]
Hey,

SPPull initially was written in JavaScript and `module.exports = sppull;` was used.
Which made some difficulties for importing the module in a usual TypeScript way.
SPPull was migrated to TypeScript, but the export style was kept for compatibility reasons.

You could check for usage examples [here](https://github.com/koltyakov/sppull/tree/master/examples/basic) and [here](https://github.com/koltyakov/sp-build-tasks/blob/master/src/tasks/sync.ts#L11).

I was thinking about eliminating this `module.exports = sppull;` in next major version, but for now you should use require and import types definition separately:

```javascript
import { AuthConfig as SPAuthConfigurator } from 'node-sp-auth-config';
import { ISPPullOptions, ISPPullContext, Download as IDownload } from 'sppull';

const Download: IDownload = require('sppull');
const sppull = Download.sppull;

(new SPAuthConfigurator()).getContext().then((context) => {

    let pullContext: ISPPullContext = <any>{
        siteUrl: context.siteUrl,
        ...context.authOptions
    };

    let pullOptions: ISPPullOptions = {
        spRootFolder: 'Shared%20Documents',
        dlRootFolder: './Downloads/Documents'
    };

    sppull(pullContext, pullOptions);

}).catch(console.log);
```

**Comment by koltyakov** [comment]
Closing this issue, feel free to reopen if you still have some questions.
