### ISSUE TITLE
FIles are not downlaoded then options.recursive is not explicitly set to false and no sub folder exists in given folder

### ISSUE THREAD

**Issue by Z3roCoder** [koltyakov/sppull#15]
Hello! I have noticed a pretty severe bug in the application.
Assuming my config looks similar to this: 

```
const result = await sppull.sppull({
        siteUrl: 'https://mySharepoint.sharepoint.com/internal',
        creds: {
            username: 'admin',
            password: 'admin'
        }
    }, {
            spRootFolder: 'Documents/project/subDir',
            dlRootFolder: 'data/sharepoint'
        });
```

And assuming the content of `https://mySharepoint.sharepoint.com/internal/Documents/project/subDir` as the following:

```
item1.xlsx
item2.xlsx
Documentation_Word.docs
```

Assuming these circumstances, the Application does not correctly detect that there are no Sub-Folders inside of  the given URL and SharePoint Folder Path, and just "hangs" forever until it receives a timeout. 

`Folders proceeding: 0 out of 0 [recursive scanning...]`

Adding an empty folder though resolves the issue and the download happens with the newly created folder, as well as the files that were inside the Sharepoint folder before.

It should be detected if there is a folder inside the given path or not, and in return call `runDownloadFilesFlat` to just return the files of the given path.

**Comment by Z3roCoder** [comment]
Taking a look over the code, I assume the problem comes from the following piece of code:
Inside `private getStructureRecursive`
```
if (foldersQueue.length === 0) {
                spRootFolder = this.options.spRootFolder;
                exitQueue = false;
            } 
```
If there are no subfolders, the foldersQueue will always be empty, thus resulting in a length of 0, setting exitQueue to false, and go through the recursion once more.

**Comment by koltyakov** [comment]
Hi, thank you! I'll take a look but after a while as I'm on vacation right now and coming back in a week.

**Comment by Z3roCoder** [comment]
Alright, and thanks for the very quick reply!

Have a nice Vacation! :)

**Comment by koltyakov** [comment]
Hi @Z3roCoder,

Once again thank you for revealing the bug, I really missed such a case.
Please check if the applied fix works for you? 
The version is merged and published to NPM (v.2.0.7).

**Comment by koltyakov** [comment]
Closing this. Feel free to re-open if you still face the issue.
