### ISSUE TITLE
Support for Custom HTTP Headers / Mixed Mode Authentication

### ISSUE THREAD

**Issue by sg-chrishasz** [koltyakov/sppull#20]
Hello @koltyakov !

First: Thank you for authoring sppull and spauth! I am using both libraries as part of my VSCode addon: SPGo (https://github.com/readysitego/spgo) and it has saved me hours of work.

A number of my users support SharePoint environments where mixed mode authentication is used, but are unable to authenticate using NTLM Credentials due to the requirement that the "X-FORMS_BASED_AUTH_ACCEPTED” header be present, with a value of "f" (this configuration forces SharePoint to use NTLM auth). 

Can you extend the sppull() function to also optionally accept a set of headers to include in all http/s calls to the SharePoint server?

Thanks!
Chris

**Comment by koltyakov** [comment]
Hi Chris,

Thank you for using my module within your VSCode extension.
I'll take a look at SPGo.

You told that you are "currently rewriting the authentication code entirely". Do you mean physical auth to SharePoint or a settings level for VSCode.
Not sure that's it's the case with SPGo (I just didn't check VSCode extensions architecture) but, in Node.js app, we use [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth) (for authentication for different scenarios) and [node-sp-auth-config](https://github.com/koltyakov/node-sp-auth-config) (for building configurations interacting with a user).

For custom headers, it's definitely feasible. I'll take a look from SPPull's side.

**Comment by koltyakov** [comment]
The same changes that mentioned in [this](https://github.com/s-KaiNet/spsave/issues/32#issuecomment-342568369) comment are also applicable to `sppull`.
The new version is published: `2.2.2`.

**Comment by sg-chrishasz** [comment]
@koltyakov thank you for the quick solution and release. I will integrate today and begin testing.
