### ISSUE TITLE
Files with ' in their name

### ISSUE THREAD

**Issue by XDjackieXD** [koltyakov/sppull#21]
to successfully download files with an apostrophe in their name, we need to replace every apostrophe in the file path with `%27` before the actual download. I fixed it by appending `.replace("'", "%27")` to `spFilePath` in the line where the rest url gets pieced together for both the simple and stream downloader in api/index.ts line 240 and 278.

**Comment by koltyakov** [comment]
Thank you, Jakob, for using the lib and reporting the issue!
I've fixed it, please check v.2.2.3. The same issue was with folder names too. So it wasn't only lines 240 and 278 causing the error. 
Also, offside comment `'` can appear multiple times in the path in theory so replace should contain regex (`.replace(/'/g, '%27')`).

**Comment by XDjackieXD** [comment]
Thanks version 2.2.3 fixed it!
