### ISSUE TITLE
Incorrect filenames + download locations when spBaseFolder == '/'

### ISSUE THREAD

**Issue by sg-chrishasz** [koltyakov/sppull#24]
sppull version 2.2.4:

When referencing the root Site Collection of a SharePoint site (`spBaseFolder` == '/'), sppull will remove all instances of the '/' character in the resulting file name, causing all files to be downloaded to the local download root, with the filename set to a concatenated string of it's folder path.
ex:
spBaseFolder == '/', SP file path == '/SiteAssets/someFile.css', downloadroot == '/downloads' will result in the file being saved as the following on local disk:
`/downloads/SiteAssetssomeFile.css`

Changing the `spBaseFolder` property to an empty string as part of configuration will fix this issue.

Even with the workaround listed above, I've created this issue as the [latest commit](https://github.com/koltyakov/sppull/commit/fc478f7230d1e55cb24de8d9111570b59422e5c4#diff-c6544576058007b56b9e602a10765197) breaks backwards compatibility, where a `spBaseFolder` set to '/' will work correctly.

**Comment by koltyakov** [comment]
Thank you, Chris!
Please check v 2.2.4.

**Comment by sg-chrishasz** [comment]
Hello @koltyakov 

Confirmed fixed in 2.2.5.  Thank you!

-Chris

**Comment by koltyakov** [comment]
Cool! Thanks for coming back with the info. Closing the issue.
