### ISSUE TITLE
500 error when downloading files outside of document libraries

### ISSUE THREAD

**Issue by sg-chrishasz** [koltyakov/sppull#25]
Hello @koltyakov !

User @tknaller found an error when using SPGo to download/synchronize files which live in SharePoint folders (e.g. not in a document library with metadata). It looks like sppull injects standard metadata fields into the api call, and SharePoint returns an error 500 when the fields don't exist.

Original issue here: https://github.com/readysitego/spgo/issues/63

Is the ability to download files outside of Document Libraries something you want to want to support with sppull?

**Comment by koltyakov** [comment]
Thanks, @sg-chrishasz,

I saw the original issue. The rare scenario where I would probably recommend provisioning hidden library.

Yet, API allows working with folders outside document libraries. So I'm going to implement the capability, I even think it worked (probably before adding some metadata-based logic).

**Comment by koltyakov** [comment]
The feature is implemented. The new version is published v2.3.0.
Tests went well, but any tests and feedback from the fields are welcome.

**Comment by sg-chrishasz** [comment]
Confirmed I can read, write, check out, and publish a file to a web folder.

Thanks for the quick turn-around @koltyakov!

**Comment by koltyakov** [comment]
Cool, glad it works. Thank you too for a quick turn-around with testing within SPGo!
