### ISSUE TITLE
Download error: JSON content in a file without ".json" extension

### ISSUE THREAD

**Issue by sg-chrishasz** [koltyakov/sppull#26]
Using sppull to download a file from SharePoint which contains only json data causes sppull or the fs object to treat the file contents as a js object, and the resulting file only contains text `[object] [object]`.

The error occurs in `downloadSimple` when json data is passed to fs.writeFile, it looks like it is not converted to a string first. I see there is a check for when the filename ends with `.json`, but there should also be a check for json data in the response.body.

_note: this error does not occur when the `downloadAsStream` function is used_

``` javascript
  private downloadSimple = (spFilePath: string, saveFilePath: string): Promise<string> => {
    return new Promise((resolve, reject) => {
      let restUrl: string =
        `${this.context.siteUrl}/_api/Web/GetFileByServerRelativeUrl(@FileServerRelativeUrl)/OpenBinaryStream` +
        `?@FileServerRelativeUrl='${this.utils.escapeURIComponent(spFilePath)}'`;

      this.spr.get(restUrl, {
        encoding: null,
        agent: this.utils.isUrlHttps(restUrl) ? this.agent : undefined
      })
        .then((response) => {
          if (/.json$/.test(saveFilePath)) {
            response.body = JSON.stringify(response.body, null, 2);
          }
          if (/.map$/.test(saveFilePath)) {
            response.body = JSON.stringify(response.body);
          }
          fs.writeFile(saveFilePath, response.body, (err) => {
            if (err) {
              return reject(err);
            }
            resolve(saveFilePath);
          });
        })
        .catch(reject);
    });
  }
```

reference Issue from SPGo: https://github.com/readysitego/spgo/issues/60

**Comment by koltyakov** [comment]
This is fixed, going to publish an update to NPM sooner, working on another issue.

**Comment by sg-chrishasz** [comment]
Confirmed fixed in SPGo. Thanks, @koltyakov!
