### ISSUE TITLE
TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by gregd72002** [koltyakov/sppull#29]
https://github.com/koltyakov/sppull/blob/master/src/api/index.ts#L93
https://github.com/koltyakov/sppull/blob/master/src/api/index.ts#L81

should state 'error.message' instead of 'err.message'

**Comment by gregd72002** [comment]
Pull request created: https://github.com/koltyakov/sppull/pull/30

**Comment by koltyakov** [comment]
Thanks! Yep, silly error, my fault. Published the update which includes your fix.
