### ISSUE TITLE
Filter error in runDownloadStrictObjects

### ISSUE THREAD

**Issue by chrishasz** [koltyakov/sppull#34]
Hello @koltyakov!   

I found an issue in sppull 2.4.0 where the filter criteria used in `runDownloadStrictObjects` to determine if the strict object is a file (does it contain a '.'), is actually checking to see if the array contains a value '.', not whether the array item contains the value '.'. Due to this, strict object downloads are not working.

See code from SPPull.ts

original:
``` typescript
const filesList: IFileBasicMetadata[] = ctx.options.strictObjects
      .filter((d) => d.split('/').slice(-1).indexOf('.') !== -1)
      .map((ServerRelativeUrl) => ({ ServerRelativeUrl }));
```

update:
``` typescript
const filesList: IFileBasicMetadata[] = ctx.options.strictObjects
      .filter((d) => d.split('/').slice(-1)[0].indexOf('.') !== -1)
      .map((ServerRelativeUrl) => ({ ServerRelativeUrl }));
```

I'm submitting a simple pull request for this shortly.

**Comment by koltyakov** [comment]
Thanks, @chrishasz!
