### ISSUE TITLE
Getting error- Unable to receive namespace authentication type with office365 sharepoint

### ISSUE THREAD

**Issue by sanjeev2315** [koltyakov/sppull#41]
When I am trying to access the main site url on browser it works and then i have mentioned same in site url with sppull and then mentioned folder to look for files under sproot folder but I a getting below error:-

Error in getFolderContent - Unable to receive namespace authentication type :unknown.

I am using username and password which i am assuming resolving to ntlm. Please help

**Comment by koltyakov** [comment]
Web's root folder can't be used. Only folders in document libraries.

SiteURL should stand for absolute site/web URL and does not contain a page URI part.

For example, when you open site in a browser it can navigate to welcome page `https://contoso/sites/site/pages/home.aspx` while SiteURL is `https://contoso/sites/site` but not the one shown in a browser. I guess, this is your issue.

**Comment by koltyakov** [comment]
Regarding authentication, based on the one which is used in your environment you should select a correct strategy. The simplest way to test if the auth works is https://github.com/koltyakov/node-sp-auth-troubleshoot

**Comment by sanjeev2315** [comment]
So my siteurl is:-
https://mycompany.sharepoint.com/sites/sitename

and sprootfolder is -
myfolder%20name

i think this is inline with what you are mentioning. When i launch my siteurl in browser with_api/web appending to it, it returns me response

**Comment by koltyakov** [comment]
Your auth strategy is not NTLM. It's SharePoint Online. SAML strategy should be picked for dev scenario. However, if MFA is configured. SAML won't work with user password, the app password is required, or switching to On-Demand auth and configuring Add-In.

**Comment by sanjeev2315** [comment]
I think its my bad, i said ntlm, it is SAMl but MFA is not enabled, so i think just username and password should work. I am troubleshooting as per your comment

**Comment by sanjeev2315** [comment]
Hey, On troubleshooting, I am getting error:- 
cannot read property length of undefined

**Comment by koltyakov** [comment]
It doesn't say anything without the state trace, but that you providing incorrect strategy+credentials. It's better to search for answers in issues in `node-sp-auth` repo or raise a question with the details in that repo if you can't really find a solution. But I can recall lots of similar questions after providing the wrong parameters.

Can suggest that it's not SAML in your case but ADFS probably configured for the tenant. You can detect it by the login page URL, if it's not a Microsoft resource it can be custom ADFS which requires more settings with credentials.

> or switching to On-Demand auth and configuring Add-In.

These options would work with ADFS as well.

**Comment by sanjeev2315** [comment]
Hey, just to add one last thing-
when i use your troubleshooter and use siteurl as https://mycompany.sharepoint.com and ADFS with username/password, it says success and prints the cookie
but if i use siteurl as https://mycompany.sharepoint.com/sites/mysite then i get the same error:-
Unable to receive namespace authentication type with office365 sharepoint.

Could you point me in a correct direction from here if possible

**Comment by koltyakov** [comment]
Cookie presence in the output it a good sign.

> but if i use siteurl as https://mycompany.sharepoint.com/sites/mysite then i get the same error:-
Unable to receive namespace authentication type with office365 sharepoint.

Not sure what it might be. I didn't face similar symptoms before. Maybe previous attempts cached something. Please check if [in a temp folder](https://github.com/s-KaiNet/node-sp-auth/blob/d23ebadf9bcdc22b646c2e398763f057d30c6b8b/src/utils/FilesHelper.ts#L8) you have incorrect creds saved. Or post a question in `node-sp-auth` repo providing these details.

Also, did you try [On-Demand auth](https://github.com/s-kainet/node-sp-auth/wiki/On-demand-authentication)? Will it also work for the root site and won't for a pathed site.

**Comment by sanjeev2315** [comment]
On-demand-auth requires electron and i am not able to install electron correctly globally or locally due to some library issues. Another thing i forgot to mention i tried downloading files directly from node-sp-auth and it worked yesterday with same site for some time then getting this error there too, so you could be right about cache related issues. I am looking for the same
