### ISSUE TITLE
Does sppull keeps all files in memory from a folder until it reads all files

### ISSUE THREAD

**Issue by sanjeev2315** [koltyakov/sppull#42]
It is more of a question rather than an issue-

1.Does sppull keeps all files in memory from a folder until it reads all files and callback triggers. In my case a folder contains 1200 files, so it will download all files and keep them in memory ? 

2. Is there any way that library process all files of a folder first and then process the sibling folder if i am running it recursively so that i can free up memory ?

**Comment by koltyakov** [comment]
It doesn't keep files in memory but only the metadata information.
There is a `recursive` option that can be disabled to download only from the specific file, then use another folder and a separate call.
I'm wondering, what's the scenario with 1200 files? Maybe a misuse? Anyways, thousands of docs is not a large number for temporarily store metadata in memory for a dev toolchain scenario.

**Comment by sanjeev2315** [comment]
yeah, I have written code to read folder structure first to read 100 folders which are siblings and then I am going into each folder to pick all 1000+ files for each of them and so on. Looks like it is serving my purpose. Thanks a lot for your help

**Comment by sanjeev2315** [comment]
Hi Andrew, Is it possible to just download metadata of files in a folders not the file itself? I mean is it even feasible?

**Comment by koltyakov** [comment]
Feasible, but easier just requesting items in a document library.

**Comment by sanjeev2315** [comment]
ok, In my case i need only metadata of around 500K files in sharepoint folders so downloading the files will take lot of time and at the end i just need metadata of all files, do we have any custom option in sppull for doing such a thing or if you can direct me how i can achieve that?

**Comment by koltyakov** [comment]
> do we have any custom option in sppull for doing such a thing

No, it's not the use case for `sppull`. You can use `sp-request` with raw REST API calls or `PnPjs`. However, 500K is too many and requesting wouldn't be a straightforward, search API or the indexing fields filtering might be needed.

**Comment by sanjeev2315** [comment]
ok, thanks Andrew, Let me explore PnPjs and figure out how it can solve my purpose. Thanks a lot for your guidence
