### ISSUE TITLE
SharePoint file status

### ISSUE THREAD

**Issue by varunsree** [koltyakov/sppull#45]
Is it possible to know the file status is Locked or not?

**Comment by koltyakov** [comment]
Hi @varunsree,

It should be possible by checking it in the usual for SP API way, which is not empty `CheckoutUserId` field value. For that purposes `metaFields` property can be used,

![image](https://user-images.githubusercontent.com/7816483/80957967-e02cb700-8e0c-11ea-9c0a-30b5b6245e7b.png)

If not null then checked out.

**Comment by varunsree** [comment]
Thanks for your quick update. But i am facing issue  regarding the response. Always got null from the metadata response.

**Comment by koltyakov** [comment]
If a status is not affected in metadata obviously there is no way to track it at all. You can use the "require checkout to edit" option, but this is not connected with the library.

Just wondering, what scenario are you covering?

**Comment by varunsree** [comment]
Actually I want to update the SharePoint files at some point in time, So at that time, the file is opened in the browser I got the error message like 'File is Locked'. So I want to check that the file is opened before the update operation is performed.

**Comment by koltyakov** [comment]
Not sure that there is a way to understand if a file is locked before an update request sent and 423 HTTP Status code is received back, at least can't recall anything like this. Anyways, it should not be a part of documents fetching with SPPull (as time delay before a file is fetched and is locked to editing can be serious) but an update logic, relying on ETags, forcing checkouts while editing, etc. if a process involves many actors changing the docs.

**Comment by koltyakov** [comment]
Going to close this.
