### ISSUE TITLE
Cannot download files containing special symbols: % or #

### ISSUE THREAD

**Issue by IgorP120** [koltyakov/sppull#47]
Files with names containing these symbols do not cause any errors, however sppull downloads only first ~400 bytes for such files and then just returns with resolved promise.

Might be related to this known SP issue: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api

**Comment by koltyakov** [comment]
Not sure that this is possible to fix universally. `*Path` methods (which allows working with some special characters in paths) were only introduced in SPO and SP2019, however the library targets SP2016 and SP2013 as well.

Will investigate. Maybe a sort of fallback logic can be added. E.g. if a special character is found try to use `*Path` method, if not presented in the API for a version of the platform, try something else.

**Comment by IgorP120** [comment]
I just tried couple of things, and found that the following change allows downloading files with names containing special symbols:

instead of **GetFileByServerRelativeUrl(@FileServerRelativeUrl)** in the URL use 

**GetFileByServerRelativePath(DecodedUrl=@FileServerRelativeUrl)**

Seems to be working for all kind of files, as far as I tested.

Thanks,
Igor

**Comment by koltyakov** [comment]
That's what I was saying `GetFileByServerRelativePath` method was introduced in SPO not so long ago, it's only presented in SP2019 forked after the time it was added in SPO code base but absents in SP2013/16:

![image](https://user-images.githubusercontent.com/7816483/81905767-dbff5700-95cd-11ea-8dfd-6b98a694a51c.png)

There are many who still use On-Prem, and it's very rare when it's SP2019.

 So for me to make it's done the plan is:
- Before download check, if special characters are in the path
  - If no special characters
    - Use `GetFileByServerRelativeUrl` as default
  - Only if special characters are presented
    - Try using `GetFileByServerRelativePath`
    - If it fails throw and error if it's really the case that in SP2016/13 a path ends up with such behavior or find another way without `GetFileByServerRelativePath` - just need to investigate

Going to spend some time on this over the weekend.

**Comment by koltyakov** [comment]
Please check the new version just published v2.6.5.
`GetFolderByServerRelativePath` and `GetFileByServerRelativePath` are incorporated into the API methods with a check and fallback to `*ByServerRelativeUrl` methods. Have testes against SPO, 2016, 2013. Looks good so far.
