### ISSUE TITLE
401 undefined

### ISSUE THREAD

**Issue by emperorpraveen** [koltyakov/sppull#48]
I am getting the following error.

![image](https://user-images.githubusercontent.com/20153145/82409212-3f104400-9a3b-11ea-8234-e4d3f58be3fa.png)

**Specs:**
SharePoint 2013
OnPremise

**My Code:**

```
var credentialOptions = {
    siteUrl: "https://ws.domain.com/content/p1",
    username: "xxxxx",     // not sure what to enter, i tried both company email and domain username.
    password: "xxxxxx",
    domain: "ws.domain.com"
};

var spr = require('sp-request').create(credentialOptions);

spr.get('https://ws.domain.com/content/p1/un/_api/web/lists/getbytitle(\'MyList\')')
    .then(function (response) {
        console.log('List Id: ' + response.body.d.Id);
    })
    .catch(function (err) {
        console.log('Ohhh, something went wrong...', err);
    });
```

**Comment by emperorpraveen** [comment]
Accidentally closed.

**Comment by koltyakov** [comment]
Hi @emperorpraveen,

You're providing incorrect credentials, so the auth library can't authenticate. 

Please check [credential options article](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-on-premise-user-credentials-authentication#credential-options), which contains samples. 

`ws.domain.com` can't be a short domain name (NetBIOS, it's the same as part of login when it's in `[[domain]]\username` format).

When a username is provided as `username@[[fqdn]]`, `domain` property shouldn't be provided simultaneously.

And, BTW, how it's connected with SPPull repository, while you referencing to `sp-request` library? ;)

**Comment by koltyakov** [comment]
Going to close the issue as answered.
