### ISSUE TITLE
sppull failing to download files containing apostrophes (') in the filename

### ISSUE THREAD

**Issue by Tiago-Altus** [koltyakov/sppull#50]
Running sppull(sppullContext, sppullOptions) returns the correct ServerRelativeUrl and SavedToLocalPath in the response. 
Filenames with no special characters are working fine but when I try with a file like "Example's.docx" the document is downloaded to my local path but the file size is 1kb and when I try opening it, it is corrupt.

I created a function to parse the error XML and I get the following error returned: 
"The file /sites/site/subsite/Shared Documents/folder/Example's.docx does not exist." when indeed it does exist. 
I tried encoding the filename but the issue remains the same after encoding.

Any ideas?

**Comment by koltyakov** [comment]
Hi @Tiago-Altus,

What version of SPPull are you using?
What version of SharePoint?

**Comment by Tiago-Altus** [comment]
sppull version 6.14.2 and sharepoint online

**Comment by koltyakov** [comment]
I guess it's Node.js version. The latest `sppull` is v2.6.5.
It's good that's SPO as recently the methods that support advanced filenames have been implemented (https://github.com/koltyakov/sppull/issues/47).
Please check if updating to v2.6.5 works for you.

**Comment by Tiago-Altus** [comment]
My apologies, ,yes I am using "sppull": "^2.6.5",

**Comment by koltyakov** [comment]
Seems I've found the issue. Please check sppull@2.6.6 which is just published

**Comment by Tiago-Altus** [comment]
Great, seems to be working now. Thanks!
