### ISSUE TITLE
Download Problem Opening the File

### ISSUE THREAD

**Issue by HeinnerXD** [koltyakov/sppull#54]
I used the "sppull" NPM package to download files from Sharepoint. But when the file is downloaded and I try to open it throw me an error:
![Captura](https://user-images.githubusercontent.com/22373770/98137011-85dde300-1e8f-11eb-860e-5ce9d97b53bc.png)
Why is this happening? What can I do to fix it?
Thank you.

This is how I code it: 

'use strict'

const { sppull } = require("sppull");

const context = {
    siteUrl: "https://adventistacol.sharepoint.com/sites/valorem/",
    creds: {
        username: "hfmayorga@adventista.edu.co",
        password: "**********"
    }
};

const options = {
    spRootFolder: "Documentos%20compartidos/Forms/AllItems/",
    dlRootFolder: './Downloads/Valorem',
    strictObjects: [
        "libroPrueba.xlsx" // Only responsive.master file from /subsite/_catalogs/masterpage
    ]
};

sppull(context, options)
    .then((downloadResults) => {
        console.log("Files are downloaded");
        console.log("For more, please check the results", JSON.stringify(downloadResults));
    })
    .catch((err) => {
        console.log("Core error has happened", err);
    });

**Comment by koltyakov** [comment]
Hi @HeinnerXD, can you translate or copy the message text, sorry don't speak Spanish?
When downloading manually this exact document, can it be opened as usual?

**Comment by HeinnerXD** [comment]
Sorry, we found the issue, was a mistake in the path of the Sharepoint file. But we had to open the file with notepad to see the message "File Not Found". Thank you.

**Comment by koltyakov** [comment]
Oh, I know what's going on. Strict object download will download the response XML body when an incorrect path to a file is provided. Can take a look into this, can it be fixed or not to return an error instead and block the download process.

The incorrect path ended up because of `/Forms/AllItems/`. Please try:

```typescript
const options = {
  spRootFolder: '/Documentos compartidos',
  dlRootFolder: './Downloads/Valorem',
  strictObjects: [ 'libroPrueba.xlsx' ]
};
```

or 

```typescript
const options = {
  spRootFolder: '/',
  dlRootFolder: './Downloads/Valorem',
  strictObjects: [ 'Documentos compartidos/libroPrueba.xlsx' ]
};
```

**Comment by HeinnerXD** [comment]
that was the solution!! thank you so much!!

**Comment by Asthay97** [comment]
> can it be fixed or no

Hi @koltyakov, I am facing an issue. So whenever I am trying to intentionally download a specific non existant file using strictobjects, its downloading an empty file instead of throwing file not found error. Is there any workaround that I can do to fix it?

**Comment by lucashthiele** [comment]
> Can take a look into this, can it be fixed or not to return an error instead and block the download process.

Hi @koltyakov,  I'm facing the same issue, whenever I try to download a file and it doesn't exist in the SharePoint directory, it doesn't return an error, but actually downloads an XML file saying that the file was not found. It would be cool if we had an easier way to check if the file was found or not.
