### ISSUE TITLE
How to download dir from an shared-link that somebody shared with me?

### ISSUE THREAD

**Issue by Zhouxiaoqing** [koltyakov/sppull#55]
Hello, everyone.
I do not have any experience of sharepoint & nodejs.
so, if this tool can download files in a dir?
I never used sharepoint ever. My friends shared an opoen-link with me, I can see the files, but I can't download all files in one step.
The URL looks like this 'https://1jjklacnz-my.sharepoint.com/personal/alog_1_jjkl_ac_nz/_layouts/15/onedrive.aspx?originalPath=aHR0cHM6Ly8xamprbGFjbnotbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvYWxvZ18xX2pqa2xfYWNfbnovRWt6ZDlYcG5KRzlJdVR3ZG85MnZtNVWTlKaExZdz9ydGltZT0xbVlDTHJpTTJFZw&id=%2Fpersonal%2Falog%5F1%5Fjjkl%5Fac%5Fnz%2FDocuments%2Ffx'.
If this tool can download these files, pls tell me how to do this.
THANKS a lot !!!

**Comment by koltyakov** [comment]
Hi @Zhouxiaoqing,

`sppull` is a developer library that allows building automation and pipelines which involve files download from SharePoint document libraries using SharePoint REST API. It is not designed for OneDrive or dealing with shared links.

`sppull` can download files from the SharePoint document library folder. It should be provided with an authentication strategy and credentials relevant to the environment - which satisfy [the authentication library](https://github.com/s-KaiNet/node-sp-auth) used under the hood.

**Comment by koltyakov** [comment]
Going to close it as answered.
