### ISSUE TITLE
Update NPM package?

### ISSUE THREAD

**Issue by michaelpavlo** [koltyakov/sppull#60]
The official sppull NPM-package is still unpatched and vulnerable. Could you update it? Much appreciated.

**Comment by koltyakov** [comment]
@michaelpavlo,

What vulnerability are you referencing?

Current dependencies state (for 2.7.1):
![image](https://user-images.githubusercontent.com/7816483/128147269-05a59883-a96a-45f9-88df-fc0ae06b0473.png)

Pushed a technical patch release 2.7.1 with where I bumped all the dependencies I could.

**Comment by koltyakov** [comment]
Going to close this item.

**Comment by michaelpavlo** [comment]
Hi, sorry for the delayed response. The older npm was dependent on an unpatched lodash version. But it is fixed now. Thank you.
