### ISSUE TITLE
Sppull library: download files returning empty array for sharepoint files

### ISSUE THREAD

**Issue by Asthay97** [koltyakov/sppull#65]
Code: ```
const context = {
    siteUrl: 'https://<tenant>.sharepoint.com',
  creds: {
    username: "<username>@<tenant>.onmicrosoft.com",
    password: "***",
    online: true
  }
};

const options2 = {
    spRootFolder: "Shared%20Documents/docverify",
    dlRootFolder: "./docverify"
  };

SPPull.download(context, options2)
  .then((downloadResults) => {
    console.log("Files are downloaded", downloadResults);
    console.log("For more, please check the results", JSON.stringify(downloadResults));
  })
  .catch((err) => {
    console.log("Core error has happened", err);
  });
```

Output: ```
Files are downloaded []
For more please check the results []
```

Screenshot of sharepoint image
![WhatsApp Image 2022-11-25 at 11 49 34 AM](https://user-images.githubusercontent.com/75947851/203898112-963738ee-5b9e-430d-83ed-d32d1b0f7490.jpeg)

**Comment by koltyakov** [comment]
Hey @Asthay97,

You have a wrong pass in configuration object:

"Shared%20Documents/docverify"

while it's just "Shared Documents" library with no folders:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/7816483/203975188-5a3d5e07-6437-4039-836d-4df86c99ac4c.png">

**Comment by Asthay97** [comment]
Hi @koltyakov, 
 Thanks a lot for helping out. The code worked after fixing the path.

**Comment by koltyakov** [comment]
Great to hear it worked. Thanks for the feedback!
