### ISSUE TITLE
camlCondition is not working

### ISSUE THREAD

**Issue by ramingar** [koltyakov/sppull#74]
Hello!

I'm using CAML to filter the amount of files downloaded from a SharePoint directory, but for some reason sppull is ignoring my camlCondition. My intention is to exclude every file where 'worklog' is not contained in the title but every file is downloaded instead, am I missing something?

```
        const context = {
            siteUrl: sharepointUrlSite,
            creds: authContext
        };

        const options = {
            spRootFolder: sharepointUrlDirectory,
            dlRootFolder: localPathDirectory,
            recursive: recursive,
            camlCondition: `
                    <Contains>
                        <FieldRef Name="Title" />
                        <Value Type="Text">worklog</Value>
                    </Contains>
            `
        }

        return sppull.download(context, options)
```
Thank you in advance!

**Comment by koltyakov** [comment]
`camlCondition` should be used in combination with `spDocLibUrl` containing the doc lib URI/name, like `Shared Documents`, to define the list context to query from using CAML. `spRootFolder` will be ignored.

**Comment by koltyakov** [comment]
Going to close as answered. Please re-open is needed.

**Comment by ramingar** [comment]
Oh, sorry for the late response. I was waiting to finish the script and ensure everything was OK to answer you.

Indeed, for some reason I overlooked this information as you suggested:

![image](https://github.com/koltyakov/sppull/assets/4048415/d0549737-90c5-48dd-8b40-2c4286dc6545)

Anyway, thank you very much for your answer!
