### ISSUE TITLE
Update README for Correct Context Initialization

### ISSUE THREAD

**Issue by AryeBorgen** [koltyakov/sppull#76]
#### Description:
The README file currently contains incorrect code for initializing the context in the usage example. The context initialization should use destructured values directly instead of referencing `context.siteUrl` and `context.authOptions`.

#### Steps to Reproduce:
1. Follow the usage example in the README file.
2. Notice that the context initialization uses `context.siteUrl` and `context.authOptions`.

#### Expected Behavior:
The context should be initialized correctly using destructured values from `getContext()`.

#### Suggested Fix:
Update the README file to reflect the correct way of initializing the context:

```typescript
import { AuthConfig as SPAuthConfigurator } from 'node-sp-auth-config';
import SPPull, { ISPPullOptions, ISPPullContext } from 'sppull';

new SPAuthConfigurator().getContext().then(({ siteUrl, authOptions }) => {

  const context: ISPPullContext = {
    siteUrl,
    ...authOptions
  } as any;

  const options: ISPPullOptions = {
    spRootFolder: 'Shared%20Documents',
    dlRootFolder: './Downloads/Documents'
  };
```

**Comment by koltyakov** [comment]
Thank you @Ary428! Merged.
