### ISSUE TITLE
Implement robust `re-downloading` (ignore files that haven't been changed since the previous download)

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/sppull#8]
Implement robust `re-downloading` (ignore files that haven't been changed since the previous download task run).
Caching metadata, versions, size, modified date, etc. algorithm to detect the same content and ignore the download of the content which is already in the local download folder.

**Comment by koltyakov** [comment]
Will reopen on demand

**Comment by thunder7553** [comment]
I'm missing this feature - any chance you'll reopen?

**Comment by koltyakov** [comment]
Hi there,

Yep, let's reopen it.
Let me think about some enhancements for re-downloading.
I can schedule it for the next week if you don't mind.

**Comment by koltyakov** [comment]
Basic optimization for re-downloading has been applied.
With local files already downloaded, SPPull checks local file size and last modified time and compares with remote files. If size is a different or modified date in SP is greater than local, the file is re-downloaded, otherwise skipped.

@thunder7553, please check if it works for you. The update is published as a v2.0.6.

**Comment by koltyakov** [comment]
Closing this one, but please reopen if you still have questions or ideas about re-download optimization.
In some scenarios, CAML-based filtration can be effective for defining date time since then data should be fetched (eg: [this test case](https://github.com/koltyakov/sppull/blob/master/test/integration/test.spec.ts#L106)), as by default SPPull walks through folders content recursively.
